//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeChat.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Menus
    {
        public int Id { get; set; }
        public string menuName { get; set; }
        public string menuPth { get; set; }
        public Nullable<int> FId { get; set; }
        public string rightId { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string remark1 { get; set; }
        public Nullable<int> flat1 { get; set; }
        public Nullable<bool> isdeleted { get; set; }
    }
}
