//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeChat.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_UserInfo
    {
        public SYS_UserInfo()
        {
            this.SYS_Log = new HashSet<SYS_Log>();
            this.WeChat_Menus = new HashSet<WeChat_Menus>();
        }
    
        public int Id { get; set; }
        public string Uname { get; set; }
        public string Upwd { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string EmployeeName { get; set; }
        public string pinyin { get; set; }
        public string idCard { get; set; }
        public string PhotoNum { get; set; }
        public string EmployeeSex { get; set; }
        public string EmployeePhone { get; set; }
        public Nullable<int> Age { get; set; }
        public string Worker { get; set; }
        public string HomeAddress { get; set; }
        public string IP { get; set; }
        public string AddTime { get; set; }
        public string remark1 { get; set; }
        public Nullable<bool> isdeleted { get; set; }
    
        public virtual ICollection<SYS_Log> SYS_Log { get; set; }
        public virtual SYS_Role SYS_Role { get; set; }
        public virtual ICollection<WeChat_Menus> WeChat_Menus { get; set; }
    }
}
