//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeChat.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Log
    {
        public int Id { get; set; }
        public string userNum { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> userRight { get; set; }
        public string logcate { get; set; }
        public string logContent { get; set; }
        public string logIp { get; set; }
        public Nullable<System.DateTime> logTime { get; set; }
        public string remark1 { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateBy { get; set; }
    
        public virtual SYS_UserInfo SYS_UserInfo { get; set; }
    }
}
