//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeChat.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Role
    {
        public SYS_Role()
        {
            this.SYS_UserInfo = new HashSet<SYS_UserInfo>();
        }
    
        public int Id { get; set; }
        public string RightName { get; set; }
        public Nullable<int> RightVle { get; set; }
        public Nullable<bool> isAdd { get; set; }
        public Nullable<bool> isUpdate { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public Nullable<bool> isdeleted { get; set; }
    
        public virtual ICollection<SYS_UserInfo> SYS_UserInfo { get; set; }
    }
}
