//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeChat.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeChat_Menus
    {
        public int Id { get; set; }
        public string MenuName { get; set; }
        public string MenuType { get; set; }
        public string MenuKeyValue { get; set; }
        public Nullable<int> MenuFid { get; set; }
        public string EventType { get; set; }
        public Nullable<int> MenuOrder { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<bool> isdeleted { get; set; }
    
        public virtual SYS_UserInfo SYS_UserInfo { get; set; }
    }
}
